### ISSUE TITLE
Needs more interactivity

### ISSUE THREAD

**Issue by danielhaaser** [MakeSchool-Tutorials/Swift-Language-Playgrounds#1]
There are not too many opportunities for students to type their own stuff, it's mostly reading.  Forcing them to write code will help them remember it.

**Comment by dionlarson** [comment]
We'll brainstorm some small exercises for each concept during instructor training. Instructors, please reply to comments below with your ideas... 😃

**Comment by dionlarson** [comment]
Please use the following format:
`<page topic>: <exercise title>`
Short description and spec for the exercise.

**Comment by dionlarson** [comment]
`type inference` exercises

**Comment by dionlarson** [comment]
`strings` exercises

**Comment by dionlarson** [comment]
`optionals` exercises

**Comment by dionlarson** [comment]
`arrays` exercises

**Comment by dionlarson** [comment]
`dictionaries` exercises

**Comment by dionlarson** [comment]
`tuples` exercises

**Comment by dionlarson** [comment]
`control flow (for/while/switch)` exercises

**Comment by dionlarson** [comment]
`functions` exercises

**Comment by dionlarson** [comment]
`enumerations` exercises

**Comment by dionlarson** [comment]
`classes & structs` exercises

**Comment by dionlarson** [comment]
`initializers` exercises

**Comment by dionlarson** [comment]
`static properties` exercises

**Comment by dionlarson** [comment]
`protocols` exercises

**Comment by iChoice** [comment]
Page 1: Var Let - 

Project for students:
Discuss properties of a person and whether it should be added as a LET or VAR:
- Age?
- Where were you born?
- Height?
- Hair Color?
- First Name?
- Last Name?

Do the same for your neighbor! Include in playground.

**Comment by funzaAcademy** [comment]
# Project: Types in Swift

We are creating an Employee model. Each employee row has the following fields. 
Can  you suggest what type will be used for each field?
- First name
- Last name
- Sex
- Employee code
- Salary
- IsFullTimeStaff

**Comment by nikolasburk** [comment]
### Page 2: Types

Provide a few variable declarations without type annotations and let the students figure out the actual types. Be evil and mislead the students by doing something like 
- `var whatAmI = "false"`
- `var whatAmI = '4'`

Include in Playground

**Comment by soggybag** [comment]
Section P02 Types. Present a list of variables where the type is inferred. Ask the student to identify the types: 

```
var age = 10        // What is the type?
var name = "Joe"
var bday = NSDate()
var shoeSize = 9.5  
```

Show another list of variable declarations where the type is inferred incorrectly, ask students to add the type: 

```
var percentCompleted = 0    // Should be Float or Double
                        // Should be string (student id numbers might looks like this: "00005763" )
var studentId = 0
var imageWidth = 0          // Should be type CGFloat
var image = nil             // Should be type UIImage?
var gender = "N"            // Should be type character
```

Include in playground
    var height = 0.0            // Should be a float

**Comment by dionlarson** [comment]
Challenges added to all pages.
