### ISSUE TITLE
P04 Optionals

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Swift-Language-Playgrounds#11]
Some questions for students on optionals
1. Can you see any situation where an optional might be useful or required? 
2. Give me an example of a variable with a type that would be a good optional value? (example username:String, would be good as an optional since a user may not have yet logged in)
3. Define an optional String with a value (var name: String? = "Joe")
4. Define an optional Float with no value (shoeSize: Float? = nil)
5. Can any type (String, Float, etc) be optional? (Yes)
6. Assign a value to shoeSize, after it is defined. (shoeSize = 9.5)
7. Display your optional clues using print() be sure to unwrap them!
8. Combine the values your created earlier into a message. It should say something like "(name) has a shoe size of (shoeSize)" ("Joe has a shoe size of 9.5")
9. Use the if let syntax to check that shoe size is set, get then print the message: "Your shoe size is: (shoeSize)"

**Comment by cliffweitzman** [comment]
This sections begins:
"/*:
## Unwrapping an Optional

When we retrieve the value from an optional, we say we "unwrap" it. This is like opening the box and seeing whether there's anything inside. We can test whether an optional has a value by comparing the whole thing to `nil`. If it is not equal to `nil`, it contains a value. Woo hoo!"

If students are already familiar with optionals then this is okay. If this is their first interaction with optionals then optionals need to be defined before students see this explanation. When reading about "opening the box" above a student that has not seen optionals before may thing "what box?"

**Comment by funzaAcademy** [comment]
var maybeAnInt: Int? = 15

let intDescription = maybeAnInt!.description
let intDescription = maybeAnInt?.description

What would the datatype of intDescription be in the above 2 cases?

**Comment by rshankras** [comment]
**Implicitly Unwrapped Optionals**

trivial - `var alwaysAString: String! = nil` is same as `var alwaysAString: String!`

Question from a student perspective?

When do we use implicitly unwrapped optionals? 
1.  When referencing interface objects in your code
   -  You might be using many UI objects and can avoid using optional bindings for each IBOutlets.

any other scenarios?

**Comment by jessetipton** [comment]
Here you'll see a Person struct that has three properties. A first name, an optional middle name, and a last name. We've also initialized a couple Person instances for testing.

```
struct Person {

    let firstName: String
    let middleName: String?
    let lastName: String

}
​
let lukeSkywalker = Person(firstName: "Mark", middleName: "Richard", lastName: "Hamill")
let sixteenthPresident = Person(firstName: "Abraham", middleName: nil, lastName: "Lincoln")
```

Write a function that prints the full name of the person in this format: {first name} {middle initial} {last name}.

```
func printFullName(person: Person) {
​
}
​
printFullName(lukeSkywalker)
printFullName(sixteenthPresident)
```
