### ISSUE TITLE
P05 Arrays

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Swift-Language-Playgrounds#12]
Array challenges 
1. Make an array of Int. Use explicit type.
2. Make an array of Double, use inferred type!
3. Make an empty array of type Character.
4. Make an array named users of type string. 
5. Add a user name to users.
6. Add another user name to users. 
7. Print the number of users in users. 
8. Add another user to users. 
9. Print the first user in users. 
10. Print the second user in users.
11. Print the last user in users. 
12. Add two more user names to users. 
13. Remove the first user from the array. 
14. Display the last user by using .last
15. Display the first user using .first 
16. Display the last user in the array using [] and count

**Comment by funzaAcademy** [comment]
The following statement needs fixing:

Notice that, just like Java's .length property, this is **not** a property, not a method. Sometimes you just want to know whether the array is empty or not:
