### ISSUE TITLE
P06 Dictionaries

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Swift-Language-Playgrounds#15]
1. Compare dictionaries to arrays? Students discuss
2. Name a situation where a dictionary might be preferable over an array? 
3. Since keys in a dictionary must be unique can you rewrite the cities dictionary so that it would work with multiple cities from the same country, assume that city names are all unique. 
4. Make a dictionary of type [String: Float]
5. Your dictionary will hold the temperature data for 3 cities. Use the key value as the city name and the set the temperature as the value. (["San Francisco": 53.7, "Oakland":56.6...])
6. Print the name of the city and it's temperature. It should look like this: "The temperature in (city name) is (value)˚"

**Comment by etodd** [comment]
More ideas:
- If you wanted to store a series of book titles in order, would you use an array or dictionary?
- If you wanted to look up the price of a book based on its title, would you use an array or dictionary?
