### ISSUE TITLE
P08: Control Flow (Challenges)

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Swift-Language-Playgrounds#16]

**Comment by nikolasburk** [comment]
**Given:** Array of strings

```
let words: [String] = ["House", "Country", "Donut", "Government", "People", "Computer", "Desk", "School"]
```

**Tasks:**
1. Create another `String` array named `wordsStartingWithD` and put every word from `words` into it that start with the letter `"D"`. (_Hint_: the function `hasPrefix()` can help you find out whether a `String` begins with a certain prefix)
2. Similar to `1.`, but instead of using a `String` array, create an array of type `Int` named `indicesOfWordsStartingWithD` and add the indices of the corresponding words that start with the letter `"D"` 
3. Create another `String` array named `lessWords` that collects every word from `words` (starting at the beginning) until there is a word that starts with the letter `"G"` (which should not be included)

**Comment by rshankras** [comment]
This is not a challenge question more of feedback on Switch statement.
1. "Every switch statment must have a default case." - Not necessary when using enums with Switch. 
2. statement typo.
