### ISSUE TITLE
P5 (Arrays)

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Swift-Language-Playgrounds#18]
This text needs to be updated, it says that count is NOT a property and NOT a method.  It is a property:

let numberOfItems = groceryList.count
print("the grocery list contains (numberOfItems) items.")
/*: 
 Notice that, just like Java's `.length` property, this is not a property, not a method.

**Comment by MichaelMeinberg** [comment]
P5 (Arrays) - Student Challenge:
- Create an array that is not mutable of all the names of the colors in a rainbow.
- Create an array that is mutable of all the students in your group.
- Pretend that 3 new students have joined your group later.   Add them to the array using the Append command.
- One student has left.  Remove the 4th person from the array.
- Pull out the 3 element of the array and put it into a variable.

**Comment by etodd** [comment]
> One student has left. Remove the 4th person from the array.

We should clarify what we mean by "nth person". People will get confused between zero- and one-based indices. Instead we could say "remove the second to last person".

**Comment by etodd** [comment]
Some ideas for revised student challenges:
- Create an immutable array containing the names of the colors in a rainbow.
- Create a mutable array containing the names of all the students in your group.
- Pretend 3 new students join your group. Add them to the array.
- Print out all the names and colors matched up like this:

```
Joe: red
Jane: orange
Bob: yellow
...
```
- Remove the second to last student from the student array and print their name.
- Print the total number of students at the end of the challenge.

**Comment by rshankras** [comment]
1. Create a mutable array with name as "cities" with these values London, New York, Delhi, Amsterdam, Berlin
2. Append Chicago to cities. 
3. Insert Tokyo at index 2. 
4. Replace Delhi with Shanghai
5. Print all the elements in array

**Comment by dionlarson** [comment]
Fixed "not a property" in fd526c694fc4089428f39b37f2432b346d458680
