### ISSUE TITLE
P15 Typo - extraneous period

### ISSUE THREAD

**Issue by zontan** [MakeSchool-Tutorials/Swift-Language-Playgrounds#22]
In the "A Simple Game" section near the bottom, there is a period in the middle of the sentence, after Ace:

"In this game, a Two is the lowest card and Ace. is the highest."

**Comment by etodd** [comment]
Also:

> So now, using the above `enum` code, create a Card `struct` with `suit` and `rank` properties, and a contstructor that accepts `suit` and `rank` parameters.

For a second I thought contstructors were some kind of awesome new Swift thing

**Comment by etodd** [comment]
> let testDeck = Deck()

Is this intentional? Should be `var` instead of `let`, since `drawOne()` is a mutating func.

> - important:
>   Does the test code above create an error?  If so, it's likely because you forgot to account for the case where there's no cards left in the deck to draw! Change your `drawOne()` method so that it returns `nil` if there's no cards left to draw.

We should probably move this paragraph _above_ the test code. I think a lot of people will stop as soon as they encounter the error, without ever reading this paragraph.

**Comment by dionlarson** [comment]
`let` on a class instance just a constant, containing a pointer. You cannot change that pointer. The declaration of each instance properties decide whether or not they can be mutated. @etodd

**Comment by dionlarson** [comment]
fd526c6

**Comment by etodd** [comment]
@dionlarson gotcha. What happened is I defined Deck as a struct instead of a class.
