### ISSUE TITLE
P11: Classes and Structs (Challenges)

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Swift-Language-Playgrounds#23]

**Comment by nikolasburk** [comment]
#### Given:

```
class Family {
    let father = "Bob"
    let mother = "Alice"
    var children = 0
}

// add a new baby to the family
func welcomeNewBorn(family: Family) -> Family {
    family.children = family.children+1
    return family
}
```

#### Tasks:
1. Instantiate an object of type `Family` named `oneFamily` and pass it to the function `addChild`. Assign the return value of that function to a variable named `anotherFamily`. What do you observe with respect to the number of children of `oneFamily` and `anotherFamily`.
2. Now change the `Family` from being a `class` to a `struct` and observe again. What happens to the number of children of `oneFamily` and `anotherFamily` this time? And why?

**Comment by dionlarson** [comment]
Modify this with daycare to or imposter child. Talk about "creating a clone" when passing to daycare function or reassigning.

**Comment by dionlarson** [comment]
Star wars and clone factory?
