### ISSUE TITLE
P01 - Var and Let Conceptual Challenge

### ISSUE THREAD

**Issue by szilardinho** [MakeSchool-Tutorials/Swift-Language-Playgrounds#27]
VAR and LET Challenge
Consider each of the following situations and specify whether it is best to use the var keyword(mutable variable) or the let keyword (constant variable).

We want to store information about the number of cars parked in a parking lot daily - A: var 
We want to record the number of units in an apartment complex -  A: let
Record your highscore in a game - A: var 
Record the number of letters in an alaphabet - A: let 
The number of teeth you have - A: var

**Comment by dionlarson** [comment]
Group discussion topic
