### ISSUE TITLE
P14 - Protocol Challenges

### ISSUE THREAD

**Issue by ocwang** [MakeSchool-Tutorials/Swift-Language-Playgrounds#33]
(1) You're building a shooting game with spaceships, helicopters, and motorcycles. Create a protocol so that all of these items can be repaired and destroyed.

Solution:

``` swift
protocol destroyable {
    repair()
    destroy()
}
```

(2) You're hosting your school's annual rock, paper, scissors competition. Each contestant has a win/loss record stored as follows:

``` swift
struct Record {
    var wins: Int
    var losses: Int

    func winPercentage() -> Double {
        return Double(wins) / (Double(losses)
    }
}
```

Two contestants have made it to the finals with the follow win/loss records:

``` swift
let recordA = Record(wins: 15, losses: 4)
let recordB = Record(wins: 17, losses: 2)
```

Implement the protocol Comparable so that the judges can determine who won the competition.

Solution:

``` swift
extension Record: Comparable {}

func ==(lhs: Record, rhs: Record) -> Bool {
    return lhs.wins == rhs.wins && lhs.losses == rhs.losses
}

func <(lhs: Record, rhs: Record) -> Bool {
    let lhsPercent = lhs.winPercentage()
    let rhsPercent = rhs.winPercentage()

    return lhsPercent < rhsPercent
}
```

**Comment by dionlarson** [comment]
Added.
