### ISSUE TITLE
P05: Arrays Challenge

### ISSUE THREAD

**Issue by jessetipton** [MakeSchool-Tutorials/Swift-Language-Playgrounds#34]
Life at the farm is hard, so we created a to do list to help!

```
var todoList: [String] = ["Wake Up", "Wash the dishes", "milk the cows"]
```
1. Since you are reading this, you are have already woken up. Let's remove that item from list.
2. Well, Ma's given you more chores. Append "Churn butter" to the end of your list.
3. It's getting later in the day, let's store how many to dos we have left in a new variable.
4. To Ma's satisfaction, we have churned that butter. Let's mark it off the list.

**Comment by dionlarson** [comment]
Added.
