### ISSUE TITLE
P15: Challenge

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Swift-Language-Playgrounds#36]
![image](https://cloud.githubusercontent.com/assets/3460171/15939480/a9143d40-2e2c-11e6-8904-32cba3c3eeff.png)

On line 133 change "a Two is the lowest card and Ace." to "a Two is the lowest card and Ace is the highest card."

**Comment by rshankras** [comment]
1. In Swift,  the term used should be initializers and not constructors.
2. "So now, using the above enum code, create a Card struct with suit and rank properties, and a constructor that accepts suit and rank parameters" - If Card is a Struct then initializers will be automatically added.

**Comment by danielhaaser** [comment]
Fixed in ead721d05f19c3ee2d607b035e5a5c33b22b9728
