### ISSUE TITLE
P03 - String - M_PI Depreciated

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Swift-Language-Playgrounds#42]
<img width="1016" alt="screen shot 2017-06-04 at 6 39 29 pm" src="https://cloud.githubusercontent.com/assets/13054451/26765965/353e8da4-4955-11e7-8e3c-dc03246187ed.png">

Line 47 (previous): let complexInterpolation = "The area of my circle is \(M_PI * radius * radius)" 

M_PI is depreciated: Xcode suggests it be replaced with "Double.pi" making the line as follows:

Line 47 (edited in pic): let complexInterpolation = "The area of my circle is \(Double.pi * radius * radius)"

**Comment by dionlarson** [comment]
Fixed in https://github.com/MakeSchool-Tutorials/Swift-Language-Playgrounds/commit/c970a5ff9970b38ad761f6600655b25b5b86308f
