### ISSUE TITLE
hoppybunny Set up the Game Scene(Setting the stage)

### ISSUE THREAD

**Issue by 2bithack** [MakeSchool-Tutorials/Swift-Language-Playgrounds#52]
In one section, it says to set the background color to sky blue, then to Add the Clouds, and displays the ground set in the picture. But it never says to add the ground and at what coordinates. and then the next page moves right into making the ground static.  Is there a text line on adding the ground that I missed?

**Comment by dionlarson** [comment]
Wrong repo. See https://github.com/MakeSchool-Tutorials/Hoppy-Bunny-SpriteKit-Swift3/issues/6

Please use the "Feedback" link at the bottom of the page for online tutorials
