### ISSUE TITLE
P08 - while loop example

### ISSUE THREAD

**Issue by yelabd** [MakeSchool-Tutorials/Swift-Language-Playgrounds#54]
The while loop explanation states that result is updated to 1,5,25,50,125 and is run 4 times. However, the explanation should state that result is updated to 1,5,25,125 and is run 3 times. 
<img width="1397" alt="screen shot 2017-06-06 at 12 39 55 am" src="https://cloud.githubusercontent.com/assets/22846929/26815336/6ff050b6-4a51-11e7-9998-53e6ebf2b9f0.png">

**Comment by dionlarson** [comment]
Fixed in 8aa90da
