### ISSUE TITLE
Hoppy Bunny 2017 - P5 and P6

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Swift-Language-Playgrounds#62]
Originally in Part 5 we are asked to replace the default game code with the following: 

<img width="651" alt="screen shot 2017-06-06 at 8 23 18 pm" src="https://user-images.githubusercontent.com/13054451/26857095-3479b4fa-4af6-11e7-8f06-2e65fbb9010c.png">

Then in Part 6 we are asked to again replace that code with the following: 

<img width="653" alt="screen shot 2017-06-06 at 8 24 15 pm" src="https://user-images.githubusercontent.com/13054451/26857106-4d955386-4af6-11e7-882e-f69a7320c2d0.png">

This is redundant and also confusing. We should instead either in Part 5 have the "import GameplayKit" in the import lines already or ask them to add the single line "import GameplayKit" to the import lines in Part 6.

This becomes confusing when we move further as the tutorial asks to add code into the functions that we added in the first picture but then deleted to put the code in the second picture.

**Comment by dionlarson** [comment]
Fixed.
