### ISSUE TITLE
Hoppy Bunny 2017 - Part 7 (Dynamic Obstacle Generation)

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Swift-Language-Playgrounds#63]
The code is not in a white code block. 

<img width="668" alt="screen shot 2017-06-06 at 8 42 23 pm" src="https://user-images.githubusercontent.com/13054451/26857471-bbff34ac-4af8-11e7-91d5-61fee6633d21.png">

**Comment by dionlarson** [comment]
Fixed.
