### ISSUE TITLE
Hoppy Bunny 2017 - P8 (Bunny Physics) Typo

### ISSUE THREAD

**Issue by BrandonTroche** [MakeSchool-Tutorials/Swift-Language-Playgrounds#64]
There is a typo. It should read "The Body Type should be Bounding Circle."

<img width="691" alt="screen shot 2017-06-06 at 9 03 21 pm" src="https://user-images.githubusercontent.com/13054451/26857860-cb45fa56-4afb-11e7-92cf-10a6b478a946.png">

**Comment by dionlarson** [comment]
Fixed.
