### ISSUE TITLE
P02 Types intro

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Swift-Language-Playgrounds#8]
Ask students what type would best fit for specific kinds of data their app might work with. Some questions for students to discuss. Imagine you are making a form in an app. There will be fields and other user interface elements that accept various types of data? 
1. Your app needs to accept a user name and hold it in a variable. What type is best for this variable?
2. Your app needs to accept a password what type should this be? 
3. Your app needs to accept a variable that holds a user's shoe size what type?
4. Your app has a UIPicker that allows a visitor to choose their gender choices are M, F, O(ther), N(to specified). 
5. Your app asks whether an applicant is older than 18? This is a check box or a switch? 
6. Your app asks how many people are in your party?

**Comment by dionlarson** [comment]
Group discussion
